### PR TITLE
[7.x] Update CwlPreconditionTesting and utilize _swift_reportFatalErrorsToDebugger

### LINKED ISSUE #478: Swift Assertions in Xcode 9.1
### What did you do?

I used  `expect { () -> Void in fatalError() }.to(throwAssertion())` in a test, which
throws a fatal error, completely stops the tests suite execution, and we get a
>  expected to raise any exception, got no exception 

test failed message

### What did you expect to happen?

 `expect { () -> Void in fatalError() }.to(throwAssertion())`  to succeed.

### What actually happened instead?

`expect { () -> Void in fatalError() }.to(throwAssertion())`  fails.

### Environment

List the software versions you're using:

 - Nimble: *7.0*
 - Xcode Version: *9.1 (9B55)* 
 - Swift Version: *4.0*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.3.1*

Maybe I'm missing something or doing something wrong, my deep apologies if that's the case.
Thanks for any feedback!

### PR DESCRIPTION
**Pull request by ikesyo**
Fixes #478. See https://github.com/Quick/Nimble/issues/478#issuecomment-395253950 for the details.

### CODE REVIEW

File: Sources/Nimble/Adapters/NimbleXCTestHandler.swift [hunk 1]
```diff
@@ -43,11 +43,19 @@ class NimbleXCTestUnavailableHandler: AssertionHandler {
...
+        #endif
+
         currentTestCase = testCase
     }
 
     @objc func testCaseDidFinish(_ testCase: XCTestCase) {
         currentTestCase = nil
+
+        #if swift(>=3.2)
+        _swift_reportFatalErrorsToDebugger = true
```
Comment (sharplet) [inline Sources/Nimble/Adapters/NimbleXCTestHandler.swift]: Would it make sense to stash the previous value so we can restore it, rather than assuming `true`?

Comment (ikesyo) [reply Sources/Nimble/Adapters/NimbleXCTestHandler.swift]: Addressed in 13f2cc8.
