### PR TITLE
Fixed issue with early test observer registration preventing console output

### LINKED ISSUE #270: No console output with Xcode 7.3
After updating to Xcode 7.3 and the newest Nimble, I am not getting any console output for tests. 

Running the tests from within Xcode does appear to be running the tests (seen from the Test navigator), but the console output doesn't report any success or failure, or any mention of individual tests passing / failing.

I am linking the following issue from Quick ([#494](https://github.com/Quick/Quick/issues/494)), but wanted to open an issue here, as we are not using Quick ourselves so it looks like an isolated Nimble issue.

Fastlane's scan output:

```
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 0     |
| Number of failures | 0     |
+--------------------+-------+
```

### PR DESCRIPTION
**Pull request by paweldudek**
This PR is an attempt to fix #270. 

It looks like that early test observer registration (aka as early as you can - in `+load`) prevents default XCTest observer from registering in latest XCTest that shipped with Xcode 7. 

That default observer is responsible for printing output to Xcode console (or Terminal when running `xcodebuild` from command line). There are several tools that rely on this output, for instance `xcpretty`. 

This simple PR adds logic that defers the moment where `CurrentTestCaseTracker` and thus allows default XCTest observer to register. 

Potential issues: There should not be any issues with `CurrentTestCaseTracker` being registered too late as we're moving the registration to next run loop cycle (which is the moment after all classes and categories get their `+load` message). However I'm entirely certain about and any input on whether this is a viable solution is welcomed. 

Or perhaps better alternatives, as I'm not a huge fan of using `dispatch_async` this way :wink: 

I've tested this against my test suite and it works just fine.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Agreed `dispatch_async` isn't usually the best, but I think it works in this case. 

I've run this locally and verified it works – thanks @paweldudek for such a quick turnaround on this :bow: I'm going to defer to @jeffh on merging.

File: Sources/Nimble/objc/CurrentTestCaseTracker.m [hunk 1]
```diff
@@ -12,7 +12,14 @@ @implementation CurrentTestCaseTracker (Register)
 
 + (void)load {
     CurrentTestCaseTracker *tracker = [CurrentTestCaseTracker sharedInstance];
-    [[XCTestObservationCenter sharedTestObservationCenter] addTestObserver:tracker];
+    // XCode 7.3 introduced a bug where early registration of a test observer prevented
+    // default XCTest test observer from being registered. That caused no longs being printed
```
Comment (morganchen12) [inline Sources/Nimble/objc/CurrentTestCaseTracker.m]: typo `longs` -> `logs` 

thanks for the quick PR!

**Comment by modocache** [comment]
LGTM, thanks for the quick response! Normally I'd defer to @jeffh, but in the interest of unbreaking people's workflow I'll merge this now. If we ever think of a more elegant approach we can fix forward.

File: Sources/Nimble/objc/CurrentTestCaseTracker.m (hunk 1 above)
Comment (modocache) [inline Sources/Nimble/objc/CurrentTestCaseTracker.m]: Nice catch! Let's fix this in another PR/commit.

**Comment by modocache** [comment]
@paweldudek mind sending a PR to bump the Nimble submodule in Quick?

File: Sources/Nimble/objc/CurrentTestCaseTracker.m (hunk 1 above)
Comment (morganchen12) [inline Sources/Nimble/objc/CurrentTestCaseTracker.m]: created #272 to address this :+1:

**Comment by paweldudek** [comment]
@modocache looks like @ashfurrow was faster than me :wink:
