### PR TITLE
Work around SR-6419

### LINKED ISSUE #481: Compilation error on Linux
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I upgraded my OSS project to use Swift 4 and tried to build the thing on a Travis Linux (Ubuntu 14.04.5) machine. The package manifest for my project:

```swift
let package = Package(
    name: "MockSix",
    dependencies: [
        .package(url: "https://github.com/Quick/Quick.git", from: "1.2.0"),
        .package(url: "https://github.com/Quick/Nimble.git", from: "7.0.2"),
    ],
    targets: [
        .target(name: "MockSix", dependencies: [], path: "Sources"),
        .testTarget(
            name: "MockSixTests",
            dependencies: ["MockSix", "Quick", "Nimble"]
        )
    ],
    swiftLanguageVersions: [4]
)
```

### What did you expect to happen?

`swift build && swift test` to execute properly.

### What actually happened instead?

There was a compilation error while the SPM was building the dependencies:

```
/home/travis/build/lvsti/MockSix/.build/checkouts/Nimble.git--3756397004363768916/Sources/Nimble/Matchers/PostNotification.swift:18:27: error: ambiguous use of 'addObserver'
        self.token = self.notificationCenter.addObserver(forName: nil, object: nil, queue: nil) { [weak self] n in
                          ^

Foundation.NotificationCenter:9:15: note: found this candidate
    open func addObserver(forName name: Foundation.NSNotification.Name?, object obj: Any?, queue: Foundation.OperationQueue?, usingBlock block: @escaping (Foundation.Notification) -> Swift.Void) -> NSObjectProtocol
              ^

Foundation.NotificationCenter:10:15: note: found this candidate
    open func addObserver(forName name: Foundation.NSNotification.Name?, object obj: Any?, queue: Foundation.OperationQueue?, using block: @escaping (Foundation.Notification) -> Swift.Void) -> NSObjectProtocol
              ^
```

### Environment

List the software versions you're using:

 - Quick: *1.2.0*
 - Nimble: *7.0.2*
 - Xcode Version: N/A
 - Swift Version: *4.0.2* (toolchain: https://swift.org/builds/swift-4.0.2-release/ubuntu1404/swift-4.0.2-RELEASE/swift-4.0.2-RELEASE-ubuntu14.04.tar.gz)
 - Swift Package Manager *Swift 4.0.0-dev*

### PR DESCRIPTION
**Pull request by ikesyo**
https://bugs.swift.org/browse/SR-6419

Should fix #481.

### CODE REVIEW

**Comment by ikesyo** [comment]
@lvsti Could you try with this branch?

File: Sources/Nimble/Matchers/PostNotification.swift [hunk 1]
```diff
@@ -15,10 +15,25 @@ internal class NotificationCollector {
...
-        self.token = self.notificationCenter.addObserver(forName: nil, object: nil, queue: nil) { [weak self] n in
-            // linux-swift gets confused by .append(n)
-            self?.observedNotifications.append(n)
-        }
+        #if os(macOS) || os(iOS) || os(tvOS) || os(watchOS)
+            self.token = self.notificationCenter.addObserver(forName: nil, object: nil, queue: nil) { [weak self] n in
+                // linux-swift gets confused by .append(n)
+                self?.observedNotifications.append(n)
+            }
+        #elseif swift(>=4.0.2) || swift(>=3.2.2)
```
Comment (ikesyo) [inline Sources/Nimble/Matchers/PostNotification.swift]: Unfortunately we can't use `#if if swift(>=x.y.z)` 😞 

https://travis-ci.org/Quick/Nimble/jobs/303516955

**Comment by lvsti** [comment]
it ran without errors: https://travis-ci.org/lvsti/MockSix/jobs/303702207 👍
